name: animex
description: "Anime 3rd part api stream."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.3
  logger: ^2.4.0
  speech_to_text: ^6.6.2
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: NetflixSans
      fonts:
        - asset: assets/fonts/NetflixSans-Light.otf
          weight: 200
        - asset: assets/fonts/NetflixSans-Regular.otf
          weight: 400
        - asset: assets/fonts/NetflixSans-Medium.otf
          weight: 500
        - asset: assets/fonts/NetflixSans-Bold.otf
          weight: 700
